# nfssext-autocheck-action/action.yml
# https://docs.github.com/en/actions/how-tos/sharing-automations/reusing-workflows

name: nfssext-autocheck
description: Automatic check for nfssext modules
inputs:
  module: 
    required: true
    type: string
  working_directory: 
    required: true
    type: string
  extra_packages: 
    required: false
    type: string
  pre_target: 
    required: false
    type: string
  texlive_cache_key:
    required: true
    type: string
outputs:
  fnttarg_ret:
    description: 'l3build fnttarg result'
    value: ${{ steps.fnttarg.outputs.BUILD_RET }}
  ctan_ret:
    description: 'l3build ctan result'
    value: ${{ steps.ctan.outputs.CTAN_RET }}
runs:
  using: "composite"
  steps:
    # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - name: Checkout repo
    #   uses: actions/checkout@v4
    # https://github.com/josephwright/siunitx/blob/549cad913591b92a3a199b7477a325866303bf29/.github/workflows/main.yaml
    - name: Update system 
      shell: bash
      run: sudo apt-get update
    - name: Install additional packages if needed
      if: ${{ inputs.extra_packages }}
      shell: bash
      run: sudo apt-get install ${{ inputs.extra_packages }}
    - name: Restore TeX Live from cache
      uses: actions/cache/restore@v4
      with:
        path: ~/texlive
        key: ${{ inputs.texlive_cache_key }}
        fail-on-cache-miss: true
      # oes angen hwn?
      # oes!
    - name: Set PATH
      shell: bash
      run: echo $HOME/texlive/bin/x86_64-linux >> $GITHUB_PATH
    - name: Run l3build fnttarg
    # oes pwrpas ddefnyddio if yma? am fod bob un yn cynnwys pre_target yn y matrix hwn, ond ydyn nhw?
      if: ${{ inputs.pre_target }}
      working-directory: ${{ inputs.working_directory }}
      id: fnttarg
      shell: bash
      run: |
        module="${{ inputs.module }}"
        allan=0
        l3build fnttarg || allan=1
        echo -e "BUILD_RET=${allan}\nbuild_ret_${module}=${allan}" >> "$GITHUB_OUTPUT" 
        cat "$GITHUB_OUTPUT"
    - name: Archive failed build output
    # run even iff previous step failed
      if: ${{ !cancelled() && !(steps.fnttarg.outputs.BUILD_RET) }}
    # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
      uses: actions/upload-artifact@v4
      with:
        name: buildfiles-${{ inputs.module }}
        path: build/fnt/*.log
        # Decide how long to keep the test output artefact:
        retention-days: 7
    - name: Run l3build
      working-directory: ${{ inputs.working_directory }}
      id: ctan
      shell: bash
      run: |
        module="${{ inputs.module }}"
        allan=0
        l3build ctan || allan=1
        echo -e "CTAN_RET=${allan}\nctan_ret_${module}=${allan}" >> "$GITHUB_OUTPUT" 
        cat "$GITHUB_OUTPUT"
        exit "$allan"
    - name: Archive failed test output
    # run even if previous step failed
      if: ${{ !cancelled() }}
      uses: zauguin/l3build-failure-artifacts@v1
      with:
        name: testfiles-${{ inputs.module }}
        # Decide how long to keep the test output artefact:
        retention-days: 7
    - name: Archive failed docs output
    # run even iff previous step failed
    # https://docs.github.com/en/actions/reference/evaluate-expressions-in-workflows-and-actions#status-check-functions
    # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
    # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution
      if: ${{ !cancelled() && steps.ctan.outcome == 'failure' }}
      # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
      uses: actions/upload-artifact@v4
      with:
        name: typeset-logs-${{ inputs.module }}
        path: build/doc/*.log
        # Decide how long to keep the test output artefact:
        retention-days: 7
    - name: Archive docs
    # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
      uses: actions/upload-artifact@v4
      with:
        name: docs-${{ inputs.module }}
        path: ${{ inputs.working_directory }}/*.pdf
        # Decide how long to keep the test output artefact:
        retention-days: 30

