# nfssext-autocheck-action/action.yml
# https://docs.github.com/en/actions/how-tos/sharing-automations/reusing-workflows

name: nfssext-autocheck
description: Automatic check for nfssext modules
inputs:
  check:
    required: true
    type: boolean
    default: false
  ctan:
    required: true
    type: boolean
    default: true
  dep_cache_key:
    required: false
    type: string
  doc:
    required: true
    type: boolean
    default: false
  doc_logs:
    required: true
    type: boolean
    default: true
  extra_packages: 
    required: false
    type: string
  extra_needs:
    required: false
    type: string
  module: 
    required: true
    type: string
  opts_check:
    required: false
    type: string
  opts_ctan:
    required: false
    type: string
  opts_doc:
    required: false
    type: string
  pre_target: 
    required: false
    type: string
  texlive_cache_key:
    required: true
    type: string
  working_directory: 
    required: true
    type: string
outputs:
  fnttarg_ret:
    description: 'l3build fnttarg result'
    value: ${{ steps.fnttarg.outputs.BUILD_RET }}
  check_ret:
    description: 'l3build check result'
    value: ${{ steps.check.outputs.CHECK_RET }}
  ctan_ret:
    description: 'l3build ctan result'
    value: ${{ steps.ctan.outputs.CTAN_RET }}
  doc_ret:
    description: 'l3build doc result'
    value: ${{ steps.doc.outputs.DOC_RET }}
runs:
  using: "composite"
  steps:
    # https://github.com/josephwright/siunitx/blob/549cad913591b92a3a199b7477a325866303bf29/.github/workflows/main.yaml
    - name: Update system 
      shell: bash
      run: sudo apt-get update
    - name: Install additional packages if needed
      if: ${{ inputs.extra_packages }}
      shell: bash
      run: sudo apt-get install ${{ inputs.extra_packages }}
    - name: Restore TeX Live from cache
      uses: actions/cache/restore@v4
      with:
        path: ~/texlive
        key: ${{ inputs.texlive_cache_key }}
        fail-on-cache-miss: true
      # oes angen hwn?
      # oes!
    - name: Set PATH
      shell: bash
      run: echo $HOME/texlive/bin/x86_64-linux >> $GITHUB_PATH
    - name: Restore dependency from cache
      if: ${{ inputs.dep_cache_key }}
      uses: actions/cache/restore@v4
      with:
        path: ~/work/nfssext/nfssext/cfr-lm/keep
        key: ${{ inputs.dep_cache_key }}
        fail-on-cache-miss: false
    - name: Run l3build fnttarg
    # oes pwrpas ddefnyddio if yma? am fod bob un yn cynnwys pre_target yn y matrix hwn, ond ydyn nhw?
      if: ${{ inputs.pre_target }}
      working-directory: ${{ inputs.working_directory }}
      id: fnttarg
      shell: bash
      run: |
        module="${{ inputs.module }}"
        allan=0
        l3build fnttarg || allan=1
        echo -e "BUILD_RET=${allan}" >> "$GITHUB_OUTPUT" 
        cat "$GITHUB_OUTPUT"
        exit $allan
    - name: Archive failed build output
    # run even iff previous step failed
      if: ${{ !cancelled() && steps.fnttarg.outcome == 'failure' }}
    # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
      uses: actions/upload-artifact@v4
      with:
        name: buildfiles-${{ inputs.module }}
        path: build/fnt/*.log
        retention-days: 7
    - name: Run l3build ctan
      if: ${{ inputs.ctan }}
      working-directory: ${{ inputs.working_directory }}
      id: ctan
      shell: bash
      run: |
        module="${{ inputs.module }}"
        opts="${{ inputs.opts_ctan }}"
        allan=0
        l3build ctan $opts || allan=1
        echo -e "CTAN_RET=${allan}" >> "$GITHUB_OUTPUT" 
        cat "$GITHUB_OUTPUT"
        echo -e "CHECK_OPTS=${opts}" >> "$GITHUB_ENV"
        echo -e "DOC_OPTS=${opts}" >> "$GITHUB_ENV"
        cat "$GITHUB_ENV"
        exit $allan
    - name: Run l3build check
      if: ${{ inputs.check && !(inputs.ctan) }}
      working-directory: ${{ inputs.working_directory }}
      id: check
      shell: bash
      run: |
        module="${{ inputs.module }}"
        opts="${{ inputs.opts_check }}"
        allan=0
        l3build check $opts || allan=1
        echo -e "CHECK_RET=${allan}" >> "$GITHUB_OUTPUT" 
        cat "$GITHUB_OUTPUT"
        echo -e "CHECK_OPTS=${opts}" >> "$GITHUB_ENV"
        cat "$GITHUB_ENV"
        exit $allan
    - name: Archive failed test output
      if: ${{ !cancelled() }}
      uses: zauguin/l3build-failure-artifacts@v1
      with:
        name: testfiles-${{ inputs.module }}${{ env.CHECK_OPTS }}
        retention-days: 7
    - name: Run l3build doc
      if: ${{ inputs.doc && !(inputs.ctan) }}
      working-directory: ${{ inputs.working_directory }}
      id: doc
      shell: bash
      run: |
        module="${{ inputs.module }}"
        opts="${{ inputs.opts_doc }}"
        allan=0
        l3build doc $opts || allan=1
        echo -e "DOC_RET=${allan}" >> "$GITHUB_OUTPUT" 
        cat "$GITHUB_OUTPUT"
        echo -e "DOC_OPTS=${opts}" >> "$GITHUB_ENV"
        cat "$GITHUB_ENV"
        exit $allan
    - name: Archive failed docs output
    # run even iff previous step failed
    # https://docs.github.com/en/actions/reference/evaluate-expressions-in-workflows-and-actions#status-check-functions
    # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
    # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution
      if: ${{ !cancelled() && (( steps.ctan.outcome == 'failure' || steps.doc.outcome == 'failure' ) || inputs.doc_logs ) }}
      # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
      uses: actions/upload-artifact@v4
      with:
        name: typeset-logs-${{ inputs.module }}${{ env.DOC_OPTS }}
        path: build/doc/*.log
        retention-days: 7
    - name: Archive docs
      # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
      if: ${{ !cancelled() && ( inputs.ctan || inputs.doc ) }}
      uses: actions/upload-artifact@v4
      with:
        name: docs-${{ inputs.module }}${{ env.DOC_OPTS }}
        path: ${{ inputs.working_directory }}/*.pdf
        retention-days: 30

