# This is a basic workflow to help you get started with Actions

# https://github.com/latex3/hyperref/blob/adc36adbc3650db73329469b43afb0ee86e3c807/.github/workflows/main.yaml
# https://github.com/josephwright/siunitx/blob/main/.github/workflows/main.yaml

name: Workflow exps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  things:
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    outputs:
      mod_a_output: ${{ steps.build_ret.outputs.build_ret_moda }}
      mod_b_output: ${{ steps.build_ret.outputs.build_ret_modb }}
      mod_c_output: ${{ steps.build_ret.outputs.build_ret_modc }}
    # don't abandon other builds if one module fails
    continue-on-error: true
    strategy:
      matrix:
        include:
          - module: mod-a
            mod_id: moda
            my_result: false
          - module: mod-b
            mod_id: modb
            my_result: false
          - module: mod-c
            mod_id: modc
            my_result: true
    name: "Test build: ${{ matrix.module }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Update system 
        run: sudo apt-get update
      - name: Return
        id: build_ret
        run: |
          # buildret="${{ steps.thing.outputs.build_ret }}"
          buildret=${{ matrix.my_result }}
          modid="${{ matrix.mod_id }}"
          if [ "$buildret" == "true" ] 
          then
            echo -e "BUILD_RET=0" >> "$GITHUB_OUTPUT"
            echo -e "build_ret_${modid}=0" >> "$GITHUB_OUTPUT"
          else
            echo -e "BUILD_RET=1" >> "$GITHUB_OUTPUT"
            echo -e "build_ret_${modid}=1" >> "$GITHUB_OUTPUT"
          fi
          cat "$GITHUB_OUTPUT"
      - name: Archive failed build output
        if: ${{ !cancelled() && !(steps.build_ret.outputs.BUILD_RET) }}
        uses: actions/upload-artifact@v4
        with:
          name: buildfiles-${{ matrix.module }}
          path: fontscripts/*.lua
          retention-days: 1

# vim: sw=2:et:ts=2:
