# This is a basic workflow to help you get started with Actions

# https://github.com/latex3/hyperref/blob/adc36adbc3650db73329469b43afb0ee86e3c807/.github/workflows/main.yaml
# https://github.com/josephwright/siunitx/blob/main/.github/workflows/main.yaml

name: Workflow exps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  things:
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    # don't abandon other builds if one module fails
    continue-on-error: true
    strategy:
      matrix:
        include:
          - module: mod-a
            my_result: false
          - module: mod-b
            my_result: false
          - module: mod-c
            my_result: true
    name: "Test build: ${{ matrix.module }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Update system 
        run: sudo apt-get update
      - name: Run true
        if: ${{ matrix.my_result }}
        id: fnttargt
        run:  echo -e "BUILD_RET=0" >> "$GITHUB_OUTPUT" 
      - name: Run false
        if: ${{ ! (matrix.my_result) }}
        id: fnttargf
        run: echo -e "BUILD_RET=1" >> "$GITHUB_OUTPUT"
      - name: Archive failed build output
        if: ${{ !cancelled() && ( !(steps.fnttargt.outputs.BUILD_RET) || !(steps.fnttarg.outputs.BUILD_RET) ) }}
        uses: actions/upload-artifact@v4
        with:
          name: buildfiles-${{ matrix.module }}
          path: fontscripts/*.lua
          retention-days: 1
      - name: Run l3build
        run: "echo ctan"
      - name: Archive docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-${{ matrix.module }}
          path: test/*.pdf
          # Decide how long to keep the test output artefact:
          retention-days: 1 


# vim: sw=2:et:ts=2:
